import MainHeaderList from "@/components/list/MainHeaderList";
import IconBreadcrumbs from "@/components/single/Breadcrumbs";
import OverViewTourGuide from "@/components/single/OverViewTourGuide";
import { baseUrl, fetchApi } from "@/utils/ferchApi";
import Head from "next/head";
import React from "react";

function SingelTourGuide({ SingelGuide }) {
  // console.log(SingelGuide);
  const {
    name,
    logo,
    tour_guide_license,
    qualification_path,
    qualification,
    languages,
    cities,
    slug,
  } = SingelGuide;
  return (
    <div>
      <Head>
        <title>tour guides </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeaderList title={"Tour Guides"} />
      <div className="flex flex-wrap items-center justify-between py-4 bg-[#f5f5f5] container mx-auto px-4">
        <IconBreadcrumbs
          links={[
            { name: "Home", slug: "/" },
            {
              name: "tour guides",
              slug: "/tour_guides",
            },
          ]}
          currentLink={slug}
        />
      </div>
      <OverViewTourGuide
        nameTourGuide={name}
        imagePersonal={logo}
        imageLicese={tour_guide_license}
        Qualification={qualification}
        QualificationPath={qualification_path}
        languages={languages}
        cities={cities}
      />
    </div>
  );
}

export default SingelTourGuide;
export async function getServerSideProps({ params, locale, query }) {
  const currency = query.currency || "USD";
  const slug = params?.slug || "";

  // const singletour = await fetchApi(
  //   `${baseUrl}/${locale}/packages/${params.slug}`
  // );
  const SingelGuide = await fetchApi(`${baseUrl}/tour_guides/${slug}`);
  return {
    props: {
      SingelGuide: SingelGuide.data,
    }, // will be passed to the page component as props
  };
}
