import Head from "next/head";
import React from "react";
import HeaderList from "@/components/list/HeaderList";
import ListTourcontainer from "@/components/list/ListTourcontainer";
import FilterDesktop from "@/components/list/FilterDesktop";
import Subscribe from "@/components/mainSections/Subscribe";
import DownLoadApp from "@/components/mainSections/DownLoadApp";
import NotMember from "@/components/mainSections/NotMember";
import Footer from "@/components/mainSections/Footer";
import FaQSection from "@/components/mainSections/FaQSection";
import MainHeaderList from "@/components/list/MainHeaderList";
import LandMarksContainer from "@/components/LandMark/LandMarksContainer";
import ListLnadMarkContainer from "@/components/LandMark/ListLnadMarkContainer";
import { baseUrl, fetchApi } from "@/utils/ferchApi";
import ListTourGuides from "@/components/tourGuides/ListTourGuides";

function TourGuides({ allTourGuides, regions }) {
  console.log(allTourGuides);
  return (
    <>
      <Head>
        <title>tour guides </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeaderList title={"Tour Guides"} />

      <div className="py-2 bg-[#f5f5f5]"> </div>
      <div className=" grid grid-cols-1 gap-5  md:grid-cols-5 mt-10 ">
        <div className="hidden md:block col-span-1">
          <FilterDesktop regions={regions} />
        </div>
        <div className="col-span-4">
          <ListTourGuides allTourGuides={allTourGuides} />
        </div>
      </div>
      {/* <FaQSection /> */}
      <Subscribe />
      {/* <DownLoadApp /> */}
      <NotMember />
      <Footer />
    </>
  );
}

export default TourGuides;
export async function getServerSideProps({ query, locale }) {
  const region_id = query.region || "1";
  const allTourGuides = await fetchApi(`${baseUrl}/${locale}/tour_guides`);
  const regions = await fetchApi(`${baseUrl}/${locale}/regions`);

  return {
    props: {
      allTourGuides: allTourGuides.data,
      regions: regions.data,
    },
  };
}
