import AboutUsSection from "@/components/aboutUs/AboutUsSection";
import NumberOfTourzable from "@/components/aboutUs/NumberOfTourzable";
import MainHeaderList from "@/components/list/MainHeaderList";
import DownLoadApp from "@/components/mainSections/DownLoadApp";
import Footer from "@/components/mainSections/Footer";
import NotMember from "@/components/mainSections/NotMember";
import Reviews from "@/components/mainSections/Reviews";
import Subscribe from "@/components/mainSections/Subscribe";
import WhyChooseUs from "@/components/mainSections/WhyChooseUs";
import { baseUrl, fetchApi } from "@/utils/ferchApi";
import Head from "next/head";
import React from "react";

function AboutUs({ aboutUs }) {
  console.log(aboutUs);
  return (
    <div>
      <Head>
        <title>list Popular Saudi Tours </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeaderList title={"About us "} />
      {/* <WhyChooseUs /> */}
      <AboutUsSection aboutUs={aboutUs} />
      {/* <NumberOfTourzable /> */}
      {/* <Reviews /> */}
      <Subscribe />
      {/* <DownLoadApp /> */}
      {/* <NotMember /> */}
      <Footer />
    </div>
  );
}

export default AboutUs;
export async function getServerSideProps({ locale, query }) {
  const aboutUs = await fetchApi(`${baseUrl}/pages/about-us?locale=${locale}`);

  return {
    props: {
      aboutUs: aboutUs.data,
    },
  };
}
