import ContactUsForm from "@/components/contactUs/ContactUsForm";
import MainHeaderList from "@/components/list/MainHeaderList";
import Footer from "@/components/mainSections/Footer";
import Subscribe from "@/components/mainSections/Subscribe";
import WhyChooseUs from "@/components/mainSections/WhyChooseUs";
import HeaderSections from "@/components/parts/HeaderSections";
import Head from "next/head";
import React from "react";

function contentUs() {
  return (
    <>
      <Head>
        <title>contentUs </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeaderList title={"contect us "} />
      <HeaderSections
        titel={"Contact us "}
        desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      />
      <ContactUsForm />
      <WhyChooseUs />
      <Subscribe />
      <Footer />
    </>
  );
}

export default contentUs;
