import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MainHeader from "@/components/mainSections/MainHeader";
import WhyChooseUs from "@/components/mainSections/WhyChooseUs";
import TourRow from "@/components/tour/TourRow ";
import Reviews from "@/components/mainSections/Reviews";
import NextTrip from "@/components/mainSections/NextTrip";
import Subscribe from "@/components/mainSections/Subscribe";
import DownLoadApp from "@/components/mainSections/DownLoadApp";
import NotMember from "@/components/mainSections/NotMember";
import Footer from "@/components/mainSections/Footer";
import HeaderSections from "@/components/parts/HeaderSections";
import OfferSection from "@/components/mainSections/OfferSection";
import ActivitiesRow from "@/components/tour/ActivitiesRow";
import FaQSection from "@/components/mainSections/FaQSection";
import LandMarkSection from "@/components/mainSections/LandMarkSection";
import { baseUrl, fetchApi } from "@/utils/ferchApi";
import { useRouter } from "next/router";
import { useEffect } from "react";
import BottonInquire from "@/components/hleper/BottonInquire";
import { useTranslation } from "react-i18next";

// const inter = Inter({ subsets: ["latin"] });

export default function Home({
  posts,
  tours,
  Activities,
  reviews,
  faqs,
  offers,
  partners,
  regions,
  snippets,
  destinations,
  settings,
}) {
  const { locales, locale, push } = useRouter();
  const { t, i18n } = useTranslation();

  return (
    <>
      <Head>
        <title>Tourzable Saudi Arabia </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BottonInquire title={"customize your trip"} goToCustomize />

      <MainHeader regions={regions} />
      <WhyChooseUs homepage snippets={snippets} />
      <HeaderSections
        titel={t("common:home.headPackages")}
        desc={t("common:home.packageDesc")}
      />
      <TourRow tours={tours} destinations={destinations} />
      <HeaderSections
        titel={t("common:home.headActivites")}
        desc={t("common:home.ActivitesDesc")}
      />
      <ActivitiesRow Activities={Activities} destinations={destinations} />
      <HeaderSections
        titel={t("common:home.LandmarkHeader")}
        desc={t("common:home.Landmarkdesc")}
      />

      <LandMarkSection regions={regions} />
      <Reviews reviews={reviews} allPartners={partners} />
      <OfferSection offers={offers} settingsOffer={settings} />
      <NextTrip posts={posts} />
      <FaQSection faqs={faqs} />
      <Subscribe />
      {/* <DownLoadApp /> */}
      {/* <NotMember /> */}
      <Footer />
    </>
  );
}

export async function getServerSideProps({ locale, query }) {
  const currency = query.currency || "USD";
  const posts = await fetchApi(`${baseUrl}/posts?locale=${locale}&limit=9`);
  const tours = await fetchApi(
    `${baseUrl}/packages?type_id=1&locale=${locale}&limit=9&currency=${currency}`
  );
  const Activities = await fetchApi(
    `${baseUrl}/packages?type_id=2&locale=${locale}&limit=9&currency=${currency}`
  );
  const reviews = await fetchApi(`${baseUrl}/reviews?limit=6&locale=${locale}`);
  const faqs = await fetchApi(`${baseUrl}/faqs?limit=4&locale=${locale}`);
  const offers = await fetchApi(
    `${baseUrl}/offers?limit=1&locale=${locale}&currency=${currency}`
  );
  const partners = await fetchApi(`${baseUrl}/partners?locale=${locale}`);
  const regions = await fetchApi(`${baseUrl}/regions?locale=${locale}`);
  const snippets = await fetchApi(`${baseUrl}/snippets?locale=${locale}`);
  const destinations = await fetchApi(
    `${baseUrl}/destinations?locale=${locale}`
  );
  const settings = await fetchApi(`${baseUrl}/settings?locale=${locale}`);

  return {
    props: {
      posts: posts.data,
      tours: tours.data,
      Activities: Activities.data,
      reviews: reviews.data,
      faqs: faqs.data,
      offers: offers.data,
      partners: partners.data,
      regions: regions.data,
      snippets: snippets.data,
      destinations: destinations.data,
      settings: settings,
    },
  };
}
