import ContactUsForm from "@/components/contactUs/ContactUsForm";
import FormCustomizeTour from "@/components/customizeTour/FormCustomizeTour";
import FromTourGuides from "@/components/hleper/FromTourGuides";
import MainHeaderList from "@/components/list/MainHeaderList";
import Footer from "@/components/mainSections/Footer";
import Subscribe from "@/components/mainSections/Subscribe";
import WhyChooseUs from "@/components/mainSections/WhyChooseUs";
import HeaderSections from "@/components/parts/HeaderSections";
import { baseUrl, fetchApi } from "@/utils/ferchApi";
import Head from "next/head";
import React from "react";

function TourGuides({ cities }) {
  // console.log(cities);
  return (
    <>
      <Head>
        <title>CUSTOMIZE YOUR TRIP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeaderList title={"CUSTOMIZE YOUR TRIP"} />
      <HeaderSections
        titel={"CUSTOMIZE YOUR TRIP"}
        desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      />
      {/* <FormCustomizeTour cities={cities} /> */}
      <FromTourGuides cities={cities} />
      <WhyChooseUs />
      <Subscribe />
      <Footer />
    </>
  );
}

export default TourGuides;
export async function getStaticProps({ locale }) {
  const cities = await fetchApi(`${baseUrl}/cities?locale=${locale}`);

  return {
    props: {
      cities: cities.data,
    },
    revalidate: 10,
  };
}
